### ISSUE TITLE
Heroku App not working and was incorrect version

### ISSUE THREAD

**Issue by ACHEZ9** [keighrim/cs105_nT#101]
When I was doing the load testing, I noticed that the second test (loading timeline) was not hitting redis at all. The heroku app has the wrong routing for this. We had made this change last Friday in lab, but it seems like the app that is running on heroku is the wrong version, or the changes were undone somehow. There are also many internal server errors, and it no longer seems like there are the partials.

**Comment by keighrim** [comment]
My last pushto heroku  in the afternoon was one of snapshots for ver 1.0. Now, however, I see 0.5 in the title of heroku app. My guess is @shuchenku pushed his working version for some test purpose.

**Comment by shuchenku** [comment]
Sorry I pushed the wrong local branch (out of date branch that has almost the same branch name). Now it should be bug free. Anything else we need to do before wrapping up and submitting?
