### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by shuchenku** [keighrim/cs105_nT#107]
TypeError: no implicit conversion of nil into String
                                   /app/routes/views.rb:   11:in `block in registered'​

TypeError: no implicit conversion of nil into String
                                   /app/routes/views.rb:   37:in `block in registered'​

get_global_timeline_view and get_timeline_view(@user) seem to be returning nil in some cases, resulting in error when push to output html

**Comment by keighrim** [comment]
```ruby 
      if $redis.exists("partial:top50")
        $redis.get("partial:top50")
      else
```
Maybe redis record expires while checking `exists` ?

**Comment by shuchenku** [comment]
Could be. This is the only place it can occur, right?

A check for nil at output << get_timeline_view(@user) would solve it.

**Comment by shuchenku** [comment]
is the fix on heroku yet?

**Comment by keighrim** [comment]
It should be on Heroku by now

**Comment by keighrim** [comment]
No, it's not. Interesting... why auto deploy not working? I'll do manual push.

**Comment by keighrim** [comment]
Okay, it's on Heroku and I set up test case 1
