### ISSUE TITLE
decide to put username in tweet DB 

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#13]
after some measuring

**Comment by keighrim** [comment]
After applying new schema, all tweets from the past doesn't show its owners. Maybe we should just wipe out db?

**Comment by shuchenku** [comment]
Yes, I wiped out and re-seeded locally. The new seed file accounts for this.

**Comment by keighrim** [comment]
I mean, on the server. I can't think of any catastrophic problem of wiping
out db on the server, though TAs will lose their tweets from the last week.

**Comment by shuchenku** [comment]
I bet TAs won't remember their username/password combination from last week. It should be fine to wipe:)

**Comment by keighrim** [comment]
Okay, just reset db on heroku, re-seeded. Everything looks fine. 
Closing this.
