### ISSUE TITLE
Tweet order

### ISSUE THREAD

**Issue by vsusaya** [keighrim/cs105_nT#25]
For a given user, new tweets appear in one order that differs from the order that another user will see their tweets. Ie; User A creates two new tweets (T1, T2), and sees them in their timeline in reverse chronological order (T2, T1, SeedTweetA, SeedTweetB). User B who follows A goes to A's profile and sees the tweets in the order (SeedTweetA, SeedTweetB, T1, T2).

Issue exists in the develop branch.

**Comment by keighrim** [comment]
Fixed by 1a567d3, closing issue.
