### ISSUE TITLE
v0.1 todos

### ISSUE THREAD

**Issue by shuchenku** [keighrim/cs105_nT#3]
1) Get the timeline model to work: Whenever a user tweets, corresponding records get added to the timeline table. Certain records should be deleted when a "unfollow" happens.
Once that is done, refactor how timeline GET requests are handled.
2) Login/Sessions
3) Organize routes

**Comment by vsusaya** [comment]
Just made a minor change to the branch to get the timeline search by user working (it was labeled as not working before)

**Comment by keighrim** [comment]
I cleaned up code style with few minor changes. Think it's time to merge to master and finalize 0.1 branch and #3.

**Comment by shuchenku** [comment]
I don't think timeline is fully functional yet. I'm making a small change to it and will refactor a few methods.

**Comment by shuchenku** [comment]
Do we not have a '/timeline' route anymore? What route displays all the subscribed feeds now?

**Comment by ACHEZ9** [comment]
I made several changes as well, including implementing following. Not sure how we can best resolve everything, we should meet tomorrow to discuss.

**Comment by ACHEZ9** [comment]
What is the best way to deal with conflicts in general? For example, I had checked the branch earlier and it was up to date, but now that there are other changes, obviously it is out of date. Is there a way for me to checkout and merge locally with the changes I have made?

**Comment by shuchenku** [comment]
@ACHEZ9 Allan, can you commit your changes (or branch this branch)? I'm refactoring some stuff too, don't want to conflict with you changes

**Comment by ACHEZ9** [comment]
Should I commit to a new branch? It seems like several things with routes have been changed as well, so I'm expecting conflicts.

**Comment by shuchenku** [comment]
Either way, as long as I can pull your changes. I think if you pull first, resolve the conflicts locally, and then push it will be fine.

**Comment by keighrim** [comment]
If you are not feeling confident with meesed up conflict, copy the files you changes (or whole directory) somewhere else, then use
`git checkout -- . && git clean -d -r`
to revert all changes. Then pull from remote. Finally manually merge locally.

**Comment by keighrim** [comment]
And IMHO, the best way to avoid conflict is to assign issues to people. To do that, first, issues need to be atomic and primitive. One can post a very specific issue then self-assign it before he/her starts to work on that topic. I believe posting and assigning within github will automatically send out notifications to the team.

**Comment by keighrim** [comment]
I'll close this tomorrow as we have gone over issues from 0.1
