### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#33]
[HEROKU] Have Codeship deploy to Heroku. Make sure tests still run.

**Comment by keighrim** [comment]
Is anyone working on this? I can see Heroku integrated in Codeship.

**Comment by shuchenku** [comment]
I was. But then I could not proceed bc I'm not the admin of this repo.

**Comment by keighrim** [comment]
Thanks for the work! Did you set up postgres on your Heroku repo?

**Comment by shuchenku** [comment]
No, I was not able to deploy through codeship, so I ended up not deploying at all. I think this might need to be done by you?

**Comment by keighrim** [comment]
Yep, I'll handle this over the weekend! Closing the issue and removing the heroku integration on codeship.

**Comment by keighrim** [comment]
hm,

**Comment by keighrim** [comment]
Is (almost) ready in afff336076201e732b79fc6a8710fce4ca520bdf, waiting for resolution of ruby version issue.

**Comment by keighrim** [comment]
Forgot the link. [Our app](https://afternoon-peak-6349.herokuapp.com/)
