### ISSUE TITLE
Set up loader.io

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#34]
[LOADTEST] Investigate and choose a way to load test your app. Use `loader.io`. Configure your app and `heroku` accordingly.

**Comment by ACHEZ9** [comment]
I can do this. We need the heroku repo set up first however. Once that is done, just let everyone know what the link is to the heroku server.

**Comment by keighrim** [comment]
It's all set. Accessible through Heroku web console. Closing the issue.
