### ISSUE TITLE
ruby version

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#37]
I have been using ruby 2.1.7, and so far nothing particularly mattered. 
However, while trying to set up hekoru repository, I noticed that they want users to specify the ruby version that an app is built on. I set it to 2.1.7 in [Gemfile](https://github.com/keighrim/cs105_nT/commit/afff336076201e732b79fc6a8710fce4ca520bdf#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R1), however this will cause a bundler problem if you are using ruby other than 2.1.7.

Please let us know which version you are on, so that we can fix the issue now and prevent any further problems.

**Comment by ACHEZ9** [comment]
I'm on 2.0. Standard issue that came with osX

**Comment by shuchenku** [comment]
I'm on 2.2.0.

**Comment by keighrim** [comment]
I removed version specification, then Heroku complaints about that but it builds anyway. Seems that we can keep it this way.
