### ISSUE TITLE
Set up `New Relic`

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#41]
from Pito: Instrument your nanoTwitter to begin collecting internal performance and timing data. While there are lots of ways to do this, for now, we will use New Relic, which is easiest available directly through Heroku. Figure out how to enable New Relic within your Heroku Configuration and get to know the options.

**Comment by ACHEZ9** [comment]
Configuration Files Committed to master. Seems to be something wrong with the develop branch, tests are running instead of launching server with "ruby app.rb"
