### ISSUE TITLE
Webserver

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#43]
From Pito: Switch web server from WebBrick; try others, measure.

**Comment by shuchenku** [comment]
Puma configurations for Heroku added. Todo: load testing with various numbers of workers/threads
Other servers we might consider trying: Unicorn (https://devcenter.heroku.com/articles/rails-unicorn)

**Comment by keighrim** [comment]
Should we consider this as done? I saw someone ran loadtest using puma and there were pluses and minuses...

**Comment by keighrim** [comment]
closed by 5c254ab9c558bdcc89c6c83ab2ed3f6d3d5cd9c0
