### ISSUE TITLE
Test for client library

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#73]
from Pito: [CLIENTLIBTEST] Write a complete set of tests for your client library demonstrating that the client library indeed works. Again the example is explained early in [SODRR].

**Comment by shuchenku** [comment]
Hey Keigh, I started on this yesterday. But if you already made progress I'll close my branch.

**Comment by keighrim** [comment]
Ooop, I just created the issue to start working. If you're on it, please continue.

**Comment by shuchenku** [comment]
okay thanks!

**Comment by keighrim** [comment]
closed by #78
