### ISSUE TITLE
Potfolio webpage

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#82]
user `gh-pages` bransh

**Comment by shuchenku** [comment]
Added the link to our github page in README.
I went for simplicity so it's not the prettiest, please feel free to make it prettier/add contents
Bug: I tried to get each of us a Github profile card to show in the team members section, but for some reason Vlad's won't load and I can't figure out why. http://lab.lepture.com/github-cards/#vsusaya|medium

**Comment by keighrim** [comment]
Wow, this looks wonderful! Thanks!

**Comment by keighrim** [comment]
closed by 2ddf3e0a6dbae779f80c65e209de0dde196b537a
