### ISSUE TITLE
Change caching 

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#83]
Instead of having JSON of timeline in redis cache, caching (partial) HTML string might speed things up a little.

**Comment by shuchenku** [comment]
JSON is still bing cached, now HTML is cached as well.
I set the HTML caches to expire after 30sec, now a new tweet will wait 30sec to show up in timeline. Bad UX and feels like cheating, but really helps load test results (can survive an attack from 2000 client now). 
Posting tweets can't handle load to well because of the complexity in add_to_timeline(). But I can't find a easy way to improve it.
Changes pushed to 91-stylesheet.

**Comment by keighrim** [comment]
Renamed `origin/91` branch to `83` branch. 

Should we consider queuing timeline build-up to bunnyMQ?

**Comment by keighrim** [comment]
I suppose #97 closes this.

**Comment by keighrim** [comment]
By the way, caching HTML snippet really helps, compare these:
[w/o HTML cache](https://heroku.loader.io/tests/f46bc93a4d4825bba2a8baa493dc751d/summaries/ea02154649b75c3a1412a80749cd4fb0)
[w/ HTML cache that expires in 3 secs](https://heroku.loader.io/tests/f46bc93a4d4825bba2a8baa493dc751d/summaries/32eedb5ef9e1016f42944d8fc2e691a2)

**Comment by ACHEZ9** [comment]
Awesome. We need to include some loader.io results in our submission. I am going to run through the three test scenarios a few times now and put them in a text file to add to our repo

**Comment by shuchenku** [comment]
I'm still applying some changes, should be available for load test shortly.

**Comment by ACHEZ9** [comment]
Any time frame? I do not have time later in the evening, so I was planning on getting it done within the hour. Thanks

**Comment by shuchenku** [comment]
I just did a few test but the results did not look as good as what we got this afternoon, not sure how much more time is needed. So feel free to make the text file, if later I get better results I'll add an update to it. Sorry for the delay!

**Comment by ACHEZ9** [comment]
Sounds good. Going to start going through the load tests now.

**Comment by keighrim** [comment]
Hey @shuchenku , are you still working on expiring JSON caching for lazy timelines? Just wanted any update.

**Comment by shuchenku** [comment]
Hey sorry guys, I pushed the wrong local branch. Fixing it.
